# Generated by Django 4.1.7 on 2023-03-19 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
